[package]
name = "xml-canonicalization"
description = "XML Canonicalisation Library in pure Rust"
authors = [
    "Lily Hopkins <lily@hpkns.uk>"
]
repository = "https://github.com/lilopkins/xml-canonicalization-rs"
version = "0.1.1"
edition = "2021"
license = "MIT"

[dependencies]
pest = "2.8.6"
pest_derive = "2.8.6"
quick-xml = "0.39.2"
regex = "1.12.3"
tracing = "0.1.44"

[dev-dependencies]
tracing-test = { version = "0.2.6", features = ["no-env-filter"] }
